import type { SelectOption } from "~/components/ui/Select";

export const COMMON_LINKS = {
    github: 'https://github.com/princecodes247/notling',

}

export const ONBOARDING_ROLE_OPTIONS: SelectOption[] = [
    { value: 'Software Engineer', label: 'Software Engineer / Tech Lead' },
    { value: 'Product Manager', label: 'Product Manager / Owner' },
    { value: 'Designer', label: 'UI/UX Designer' },
    { value: 'Founder / CEO', label: 'Founder / Executive' },
    { value: 'Researcher / Student', label: 'Researcher / Student' },
];

export interface EmojiData {
  emoji: string;
  name: string;
  category: 'objects' | 'symbols' | 'smileys' | 'nature' | 'places';
  keywords: string;
}

export const EMOJI_LIST: EmojiData[] = [
  // Objects & Files
  { emoji: '📁', name: 'Folder', category: 'objects', keywords: 'folder directory file storage' },
  { emoji: '📂', name: 'Open Folder', category: 'objects', keywords: 'open folder directory' },
  { emoji: '📄', name: 'Document', category: 'objects', keywords: 'page paper document text file' },
  { emoji: '📝', name: 'Memo', category: 'objects', keywords: 'pencil memo note write text' },
  { emoji: '📌', name: 'Pushpin', category: 'objects', keywords: 'pin pushpin mark attach' },
  { emoji: '📍', name: 'Round Pin', category: 'objects', keywords: 'location pin mark point' },
  { emoji: '📎', name: 'Paperclip', category: 'objects', keywords: 'clip paperclip attachment link' },
  { emoji: '📋', name: 'Clipboard', category: 'objects', keywords: 'clipboard list tasks todo' },
  { emoji: '📊', name: 'Bar Chart', category: 'objects', keywords: 'chart analytics data graph' },
  { emoji: '📈', name: 'Chart Up', category: 'objects', keywords: 'growth chart up trending' },
  { emoji: '📉', name: 'Chart Down', category: 'objects', keywords: 'chart down decrease trend' },
  { emoji: '🏷️', name: 'Tag', category: 'objects', keywords: 'label tag category price' },
  { emoji: '🗓️', name: 'Calendar', category: 'objects', keywords: 'calendar schedule date plan' },
  { emoji: '📅', name: 'Date', category: 'objects', keywords: 'calendar date event time' },
  { emoji: '📇', name: 'Card Index', category: 'objects', keywords: 'contacts card index roll' },
  { emoji: '🗞️', name: 'Newspaper', category: 'objects', keywords: 'news newspaper article paper' },
  { emoji: '💼', name: 'Briefcase', category: 'objects', keywords: 'work briefcase job business' },
  { emoji: '📦', name: 'Package', category: 'objects', keywords: 'box package shipping delivery' },
  { emoji: '📮', name: 'Mailbox', category: 'objects', keywords: 'post mailbox mail letter' },
  { emoji: '📧', name: 'Email', category: 'objects', keywords: 'email message mail letter' },
  { emoji: '✉️', name: 'Envelope', category: 'objects', keywords: 'envelope mail message letter' },
  { emoji: '💻', name: 'Laptop', category: 'objects', keywords: 'computer laptop tech code macbook' },
  { emoji: '🖥️', name: 'Desktop', category: 'objects', keywords: 'screen monitor desktop pc' },
  { emoji: '📱', name: 'Mobile', category: 'objects', keywords: 'phone mobile iphone smartphone' },
  { emoji: '⌨️', name: 'Keyboard', category: 'objects', keywords: 'keyboard type code key' },
  { emoji: '🖱️', name: 'Mouse', category: 'objects', keywords: 'mouse click pointer tech' },
  { emoji: '🖨️', name: 'Printer', category: 'objects', keywords: 'printer print paper doc' },
  { emoji: '📷', name: 'Camera', category: 'objects', keywords: 'camera photo picture image' },
  { emoji: '🔒', name: 'Lock', category: 'objects', keywords: 'lock secret security private' },
  { emoji: '🔓', name: 'Unlock', category: 'objects', keywords: 'unlock open security access' },
  { emoji: '🔑', name: 'Key', category: 'objects', keywords: 'key access password secret' },
  { emoji: '🔨', name: 'Hammer', category: 'objects', keywords: 'tool build fix hammer' },
  { emoji: '🛠️', name: 'Tools', category: 'objects', keywords: 'tools build repair config dev' },
  { emoji: '⚙️', name: 'Settings', category: 'objects', keywords: 'gear settings config options' },
  { emoji: '🧪', name: 'Test Tube', category: 'objects', keywords: 'science test lab experiment' },
  { emoji: '🔬', name: 'Microscope', category: 'objects', keywords: 'science research inspect zoom' },
  { emoji: '💡', name: 'Idea', category: 'objects', keywords: 'lightbulb idea smart light' },
  { emoji: '🕯️', name: 'Candle', category: 'objects', keywords: 'candle light focus cozy' },
  { emoji: '📚', name: 'Books', category: 'objects', keywords: 'books study read library learn' },
  { emoji: '📖', name: 'Book', category: 'objects', keywords: 'open book reading doc story' },
  { emoji: '🔖', name: 'Bookmark', category: 'objects', keywords: 'bookmark save mark tag' },
  { emoji: '🎨', name: 'Art Palette', category: 'objects', keywords: 'design art palette color paint' },
  { emoji: '🎬', name: 'Clapper', category: 'objects', keywords: 'movie video film media' },
  { emoji: '🎧', name: 'Headphones', category: 'objects', keywords: 'music audio podcast sound' },
  { emoji: '🎤', name: 'Microphone', category: 'objects', keywords: 'voice audio mic record' },
  { emoji: '🎵', name: 'Music Note', category: 'objects', keywords: 'music song note audio' },

  // Symbols & Badges
  { emoji: '🚀', name: 'Rocket', category: 'symbols', keywords: 'launch rocket fast ship project' },
  { emoji: '🔥', name: 'Fire', category: 'symbols', keywords: 'fire hot flame trending popular' },
  { emoji: '✨', name: 'Sparkles', category: 'symbols', keywords: 'magic sparkles clean star new' },
  { emoji: '🎯', name: 'Target', category: 'symbols', keywords: 'goal target aim bullseye ok' },
  { emoji: '⚡', name: 'Lightning', category: 'symbols', keywords: 'zap fast flash power electric' },
  { emoji: '🌟', name: 'Glow Star', category: 'symbols', keywords: 'star favorite top featured' },
  { emoji: '⭐', name: 'Star', category: 'symbols', keywords: 'star rating bookmark favorite' },
  { emoji: '💎', name: 'Gem', category: 'symbols', keywords: 'diamond gem premium luxury' },
  { emoji: '🏆', name: 'Trophy', category: 'symbols', keywords: 'trophy win reward champion' },
  { emoji: '🥇', name: '1st Medal', category: 'symbols', keywords: 'medal gold first win' },
  { emoji: '🎖️', name: 'Medal', category: 'symbols', keywords: 'medal badge honor award' },
  { emoji: '🎁', name: 'Gift', category: 'symbols', keywords: 'gift present surprise offer' },
  { emoji: '👑', name: 'Crown', category: 'symbols', keywords: 'crown king queen vip leader' },
  { emoji: '♟️', name: 'Chess', category: 'symbols', keywords: 'chess strategy plan game' },
  { emoji: '🎮', name: 'Gaming', category: 'symbols', keywords: 'game controller gaming play' },
  { emoji: '🎲', name: 'Dice', category: 'symbols', keywords: 'dice random game luck' },
  { emoji: '🧩', name: 'Puzzle', category: 'symbols', keywords: 'puzzle piece match component' },
  { emoji: '🧠', name: 'Brain', category: 'symbols', keywords: 'brain mind think logic smart' },
  { emoji: '👁️', name: 'Eye', category: 'symbols', keywords: 'eye view see observe watch' },
  { emoji: '💭', name: 'Thought', category: 'symbols', keywords: 'thought bubble think idea' },
  { emoji: '💬', name: 'Chat', category: 'symbols', keywords: 'comment message chat discuss' },
  { emoji: '🔍', name: 'Search', category: 'symbols', keywords: 'search find magnifying glass' },
  { emoji: '🔮', name: 'Crystal Ball', category: 'symbols', keywords: 'magic future vision crystal' },
  { emoji: '🧿', name: 'Nazar', category: 'symbols', keywords: 'eye lucky protection evil' },
  { emoji: '🌐', name: 'Globe', category: 'symbols', keywords: 'web world internet global' },
  { emoji: '🧭', name: 'Compass', category: 'symbols', keywords: 'explore navigate direction roadmap' },
  { emoji: '⚓', name: 'Anchor', category: 'symbols', keywords: 'anchor marine boat stable' },
  { emoji: '❤️', name: 'Red Heart', category: 'symbols', keywords: 'heart love like red' },
  { emoji: '💖', name: 'Sparkle Heart', category: 'symbols', keywords: 'heart sparkle love like' },
  { emoji: '💙', name: 'Blue Heart', category: 'symbols', keywords: 'heart blue like info' },
  { emoji: '💚', name: 'Green Heart', category: 'symbols', keywords: 'heart green ok success' },
  { emoji: '💛', name: 'Yellow Heart', category: 'symbols', keywords: 'heart yellow star warm' },
  { emoji: '💜', name: 'Purple Heart', category: 'symbols', keywords: 'heart purple magic' },
  { emoji: '🖤', name: 'Black Heart', category: 'symbols', keywords: 'heart black dark' },
  { emoji: '🤍', name: 'White Heart', category: 'symbols', keywords: 'heart white light' },
  { emoji: '💯', name: '100', category: 'symbols', keywords: 'hundred percent perfect 100 score' },
  { emoji: '✅', name: 'Check Mark', category: 'symbols', keywords: 'done check success ok completed' },
  { emoji: '❌', name: 'Cross Mark', category: 'symbols', keywords: 'x cancel wrong fail error' },
  { emoji: '⚠️', name: 'Warning', category: 'symbols', keywords: 'warning alert caution danger' },
  { emoji: '🚫', name: 'Forbidden', category: 'symbols', keywords: 'no stop forbidden block' },
  { emoji: '♻️', name: 'Recycle', category: 'symbols', keywords: 'loop sync recycle refresh' },
  { emoji: '💲', name: 'Dollar', category: 'symbols', keywords: 'money dollar finance cost' },
  { emoji: '🚩', name: 'Triangular Flag', category: 'symbols', keywords: 'flag mark milestone red' },

  // Smileys & People
  { emoji: '😀', name: 'Grinning', category: 'smileys', keywords: 'happy smile grin face' },
  { emoji: '🙂', name: 'Slight Smile', category: 'smileys', keywords: 'happy smile face' },
  { emoji: '😊', name: 'Blush Smile', category: 'smileys', keywords: 'happy blush smile face' },
  { emoji: '😎', name: 'Cool', category: 'smileys', keywords: 'cool sunglasses boss face' },
  { emoji: '🤓', name: 'Nerd', category: 'smileys', keywords: 'nerd glasses smart tech' },
  { emoji: '🧐', name: 'Monocle', category: 'smileys', keywords: 'inspect curious monocle' },
  { emoji: '🤩', name: 'Star Struck', category: 'smileys', keywords: 'star excited amazed wow' },
  { emoji: '🥳', name: 'Party', category: 'smileys', keywords: 'party celebration celebrate hat' },
  { emoji: '🤖', name: 'Robot', category: 'smileys', keywords: 'bot robot ai tech machine' },
  { emoji: '👾', name: 'Monster', category: 'smileys', keywords: 'game pixel alien arcade' },
  { emoji: '👻', name: 'Ghost', category: 'smileys', keywords: 'ghost Halloween spook fun' },
  { emoji: '💀', name: 'Skull', category: 'smileys', keywords: 'skull dead danger funny' },
  { emoji: '👽', name: 'Alien', category: 'smileys', keywords: 'alien space ufo sci-fi' },
  { emoji: '🤠', name: 'Cowboy', category: 'smileys', keywords: 'cowboy hat face fun' },
  { emoji: '😷', name: 'Mask', category: 'smileys', keywords: 'mask health safe sick' },
  { emoji: '🤫', name: 'Quiet', category: 'smileys', keywords: 'shh secret quiet silent' },
  { emoji: '🥱', name: 'Yawning', category: 'smileys', keywords: 'yawn bored tired sleep' },
  { emoji: '😴', name: 'Sleeping', category: 'smileys', keywords: 'sleep zzz night rest' },
  { emoji: '🤯', name: 'Exploding Head', category: 'smileys', keywords: 'mindblown wow shock mind' },
  { emoji: '😇', name: 'Angel', category: 'smileys', keywords: 'angel halo innocent good' },
  { emoji: '🐶', name: 'Dog', category: 'smileys', keywords: 'dog puppy pet animal' },
  { emoji: '🐱', name: 'Cat', category: 'smileys', keywords: 'cat kitty pet animal' },
  { emoji: '🦊', name: 'Fox', category: 'smileys', keywords: 'fox animal smart cute' },
  { emoji: '🦁', name: 'Lion', category: 'smileys', keywords: 'lion king animal wild' },
  { emoji: '🐼', name: 'Panda', category: 'smileys', keywords: 'panda cute animal bear' },
  { emoji: '🐻', name: 'Bear', category: 'smileys', keywords: 'bear wild animal cute' },
  { emoji: '🐺', name: 'Wolf', category: 'smileys', keywords: 'wolf pack wild animal' },
  { emoji: '🐵', name: 'Monkey', category: 'smileys', keywords: 'monkey fun ape animal' },
  { emoji: '🐸', name: 'Frog', category: 'smileys', keywords: 'frog animal cute green' },
  { emoji: '🐙', name: 'Octopus', category: 'smileys', keywords: 'octopus sea ocean animal' },
  { emoji: '🐝', name: 'Bee', category: 'smileys', keywords: 'bee bug honey insect' },
  { emoji: '🦋', name: 'Butterfly', category: 'smileys', keywords: 'butterfly nature pretty insect' },
  { emoji: '🦉', name: 'Owl', category: 'smileys', keywords: 'owl wise night bird' },
  { emoji: '🦄', name: 'Unicorn', category: 'smileys', keywords: 'unicorn magic rare startup' },

  // Nature & Food
  { emoji: '🌸', name: 'Blossom', category: 'nature', keywords: 'flower blossom sakura spring' },
  { emoji: '🌺', name: 'Hibiscus', category: 'nature', keywords: 'flower floral tropical pink' },
  { emoji: '🌻', name: 'Sunflower', category: 'nature', keywords: 'sunflower yellow summer flower' },
  { emoji: '🌴', name: 'Palm Tree', category: 'nature', keywords: 'palm tree beach tropical summer' },
  { emoji: '🌲', name: 'Pine Tree', category: 'nature', keywords: 'tree pine evergreen forest' },
  { emoji: '🌿', name: 'Herb', category: 'nature', keywords: 'leaf herb plant green fresh' },
  { emoji: '🍀', name: '4-Leaf Clover', category: 'nature', keywords: 'clover luck irish green' },
  { emoji: '🍁', name: 'Maple Leaf', category: 'nature', keywords: 'autumn maple leaf fall' },
  { emoji: '🌾', name: 'Rice Sheaf', category: 'nature', keywords: 'grain harvest nature plant' },
  { emoji: '☀️', name: 'Sun', category: 'nature', keywords: 'sun bright day weather' },
  { emoji: '🌙', name: 'Moon', category: 'nature', keywords: 'moon night dark space' },
  { emoji: '⛅', name: 'Sun Cloud', category: 'nature', keywords: 'cloud sun weather sky' },
  { emoji: '🌧️', name: 'Rain', category: 'nature', keywords: 'rain cloud weather sky' },
  { emoji: '❄️', name: 'Snowflake', category: 'nature', keywords: 'snow cold winter ice' },
  { emoji: '🌊', name: 'Wave', category: 'nature', keywords: 'ocean wave sea water surf' },
  { emoji: '☕', name: 'Coffee', category: 'nature', keywords: 'coffee cup hot drink tea' },
  { emoji: '🍵', name: 'Matcha Tea', category: 'nature', keywords: 'tea matcha drink green' },
  { emoji: '🍷', name: 'Wine', category: 'nature', keywords: 'wine drink glass alcohol' },
  { emoji: '🍺', name: 'Beer', category: 'nature', keywords: 'beer drink pub cheers' },
  { emoji: '🥤', name: 'Cup with Straw', category: 'nature', keywords: 'soda drink cup juice' },
  { emoji: '🍕', name: 'Pizza', category: 'nature', keywords: 'pizza food slice snack' },
  { emoji: '🍔', name: 'Burger', category: 'nature', keywords: 'burger food fast food' },
  { emoji: '🍟', name: 'Fries', category: 'nature', keywords: 'french fries food snack' },
  { emoji: '🌭', name: 'Hot Dog', category: 'nature', keywords: 'hotdog food snack' },
  { emoji: '🍿', name: 'Popcorn', category: 'nature', keywords: 'popcorn movie snack cinema' },
  { emoji: '🌮', name: 'Taco', category: 'nature', keywords: 'taco mexican food' },
  { emoji: '🥗', name: 'Salad', category: 'nature', keywords: 'salad healthy green food' },
  { emoji: '🍣', name: 'Sushi', category: 'nature', keywords: 'sushi japanese food fish' },
  { emoji: '🍎', name: 'Red Apple', category: 'nature', keywords: 'apple fruit red healthy' },
  { emoji: '🍓', name: 'Strawberry', category: 'nature', keywords: 'strawberry fruit berry sweet' },
  { emoji: '🥑', name: 'Avocado', category: 'nature', keywords: 'avocado green fruit food' },
  { emoji: '🍩', name: 'Donut', category: 'nature', keywords: 'donut sweet pastry food' },
  { emoji: '🎂', name: 'Birthday Cake', category: 'nature', keywords: 'cake birthday celebration dessert' },

  // Places & Travel
  { emoji: '🏠', name: 'House', category: 'places', keywords: 'house home building' },
  { emoji: '🏢', name: 'Office', category: 'places', keywords: 'building office business company' },
  { emoji: '🏦', name: 'Bank', category: 'places', keywords: 'bank finance money building' },
  { emoji: '🏛️', name: 'Classical Building', category: 'places', keywords: 'museum bank history building' },
  { emoji: '🏝️', name: 'Island', category: 'places', keywords: 'island beach tropical vacation' },
  { emoji: '🛸', name: 'UFO', category: 'places', keywords: 'ufo alien space travel' },
  { emoji: '✈️', name: 'Airplane', category: 'places', keywords: 'plane flight travel airport' },
  { emoji: '🚗', name: 'Car', category: 'places', keywords: 'car vehicle drive travel' },
  { emoji: '🏎️', name: 'Racing Car', category: 'places', keywords: 'race car fast speed' },
  { emoji: '🚲', name: 'Bicycle', category: 'places', keywords: 'bike bicycle ride sports' },
  { emoji: '🛵', name: 'Scooter', category: 'places', keywords: 'scooter moped delivery drive' },
  { emoji: '🚆', name: 'Train', category: 'places', keywords: 'train transit rail travel' },
  { emoji: '🎡', name: 'Ferris Wheel', category: 'places', keywords: 'fun park carnival theme' },
  { emoji: '🎢', name: 'Roller Coaster', category: 'places', keywords: 'coaster ride thrill park' },
  { emoji: '⛺', name: 'Tent', category: 'places', keywords: 'camp tent outdoor trip' },
  { emoji: '🏖️', name: 'Beach', category: 'places', keywords: 'beach umbrella sea sun vacation' },
  { emoji: '火山', name: 'Volcano', category: 'places', keywords: 'volcano nature lava hot' },
  { emoji: '🗻', name: 'Mount Fuji', category: 'places', keywords: 'mountain fuji japan nature' },
];

export const EMOJI_OPTIONS = EMOJI_LIST.map((e) => e.emoji);