/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardFoldersRouteImport } from './routes/dashboard.folders'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTrashRouteImport } from './routes/dashboard.trash'
import { Route as SharePageIdRouteImport } from './routes/share.$pageId'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth.callback.$provider'
import { Route as DashboardDbDatabaseIdRouteImport } from './routes/dashboard.db.$databaseId'
import { Route as DashboardPPageIdRouteImport } from './routes/dashboard.p.$pageId'
import { Route as ShareFormShareTokenRouteImport } from './routes/share.form.$shareToken'
import { Route as WSlugPPageIdRouteImport } from './routes/w.$slug.p.$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoldersRoute = DashboardFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const SharePageIdRoute = SharePageIdRouteImport.update({
  id: '/share/$pageId',
  path: '/share/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDbDatabaseIdRoute = DashboardDbDatabaseIdRouteImport.update({
  id: '/db/$databaseId',
  path: '/db/$databaseId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPPageIdRoute = DashboardPPageIdRouteImport.update({
  id: '/p/$pageId',
  path: '/p/$pageId',
  getParentRoute: () => DashboardRoute,
} as any)
const ShareFormShareTokenRoute = ShareFormShareTokenRouteImport.update({
  id: '/share/form/$shareToken',
  path: '/share/form/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugPPageIdRoute = WSlugPPageIdRouteImport.update({
  id: '/p/$pageId',
  path: '/p/$pageId',
  getParentRoute: () => WSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/dashboard/folders': typeof DashboardFoldersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$pageId': typeof SharePageIdRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/db/$databaseId': typeof DashboardDbDatabaseIdRoute
  '/dashboard/p/$pageId': typeof DashboardPPageIdRoute
  '/share/form/$shareToken': typeof ShareFormShareTokenRoute
  '/w/$slug/p/$pageId': typeof WSlugPPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/dashboard/folders': typeof DashboardFoldersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$pageId': typeof SharePageIdRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/db/$databaseId': typeof DashboardDbDatabaseIdRoute
  '/dashboard/p/$pageId': typeof DashboardPPageIdRoute
  '/share/form/$shareToken': typeof ShareFormShareTokenRoute
  '/w/$slug/p/$pageId': typeof WSlugPPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/dashboard/folders': typeof DashboardFoldersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$pageId': typeof SharePageIdRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/db/$databaseId': typeof DashboardDbDatabaseIdRoute
  '/dashboard/p/$pageId': typeof DashboardPPageIdRoute
  '/share/form/$shareToken': typeof ShareFormShareTokenRoute
  '/w/$slug/p/$pageId': typeof WSlugPPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/cookies'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/dashboard/folders'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/share/$pageId'
    | '/w/$slug'
    | '/dashboard/'
    | '/auth/callback/$provider'
    | '/dashboard/db/$databaseId'
    | '/dashboard/p/$pageId'
    | '/share/form/$shareToken'
    | '/w/$slug/p/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/dashboard/folders'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/share/$pageId'
    | '/w/$slug'
    | '/dashboard'
    | '/auth/callback/$provider'
    | '/dashboard/db/$databaseId'
    | '/dashboard/p/$pageId'
    | '/share/form/$shareToken'
    | '/w/$slug/p/$pageId'
  id:
    | '__root__'
    | '/'
    | '/acceptable-use'
    | '/cookies'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/dashboard/folders'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/share/$pageId'
    | '/w/$slug'
    | '/dashboard/'
    | '/auth/callback/$provider'
    | '/dashboard/db/$databaseId'
    | '/dashboard/p/$pageId'
    | '/share/form/$shareToken'
    | '/w/$slug/p/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  SharePageIdRoute: typeof SharePageIdRoute
  WSlugRoute: typeof WSlugRouteWithChildren
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
  ShareFormShareTokenRoute: typeof ShareFormShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/folders': {
      id: '/dashboard/folders'
      path: '/folders'
      fullPath: '/dashboard/folders'
      preLoaderRoute: typeof DashboardFoldersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/share/$pageId': {
      id: '/share/$pageId'
      path: '/share/$pageId'
      fullPath: '/share/$pageId'
      preLoaderRoute: typeof SharePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/db/$databaseId': {
      id: '/dashboard/db/$databaseId'
      path: '/db/$databaseId'
      fullPath: '/dashboard/db/$databaseId'
      preLoaderRoute: typeof DashboardDbDatabaseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/p/$pageId': {
      id: '/dashboard/p/$pageId'
      path: '/p/$pageId'
      fullPath: '/dashboard/p/$pageId'
      preLoaderRoute: typeof DashboardPPageIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/share/form/$shareToken': {
      id: '/share/form/$shareToken'
      path: '/share/form/$shareToken'
      fullPath: '/share/form/$shareToken'
      preLoaderRoute: typeof ShareFormShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/p/$pageId': {
      id: '/w/$slug/p/$pageId'
      path: '/p/$pageId'
      fullPath: '/w/$slug/p/$pageId'
      preLoaderRoute: typeof WSlugPPageIdRouteImport
      parentRoute: typeof WSlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFoldersRoute: typeof DashboardFoldersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDbDatabaseIdRoute: typeof DashboardDbDatabaseIdRoute
  DashboardPPageIdRoute: typeof DashboardPPageIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFoldersRoute: DashboardFoldersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDbDatabaseIdRoute: DashboardDbDatabaseIdRoute,
  DashboardPPageIdRoute: DashboardPPageIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface WSlugRouteChildren {
  WSlugPPageIdRoute: typeof WSlugPPageIdRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugPPageIdRoute: WSlugPPageIdRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  SharePageIdRoute: SharePageIdRoute,
  WSlugRoute: WSlugRouteWithChildren,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
  ShareFormShareTokenRoute: ShareFormShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
