/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardFoldersRouteImport } from './routes/dashboard.folders'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as SharePageIdRouteImport } from './routes/share.$pageId'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth.callback.$provider'
import { Route as DashboardPPageIdRouteImport } from './routes/dashboard.p.$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoldersRoute = DashboardFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const SharePageIdRoute = SharePageIdRouteImport.update({
  id: '/share/$pageId',
  path: '/share/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPPageIdRoute = DashboardPPageIdRouteImport.update({
  id: '/p/$pageId',
  path: '/p/$pageId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/folders': typeof DashboardFoldersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/share/$pageId': typeof SharePageIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/p/$pageId': typeof DashboardPPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/folders': typeof DashboardFoldersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/share/$pageId': typeof SharePageIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/p/$pageId': typeof DashboardPPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/folders': typeof DashboardFoldersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/share/$pageId': typeof SharePageIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/p/$pageId': typeof DashboardPPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/folders'
    | '/dashboard/settings'
    | '/share/$pageId'
    | '/dashboard/'
    | '/auth/callback/$provider'
    | '/dashboard/p/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/dashboard/folders'
    | '/dashboard/settings'
    | '/share/$pageId'
    | '/dashboard'
    | '/auth/callback/$provider'
    | '/dashboard/p/$pageId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/folders'
    | '/dashboard/settings'
    | '/share/$pageId'
    | '/dashboard/'
    | '/auth/callback/$provider'
    | '/dashboard/p/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SharePageIdRoute: typeof SharePageIdRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/folders': {
      id: '/dashboard/folders'
      path: '/folders'
      fullPath: '/dashboard/folders'
      preLoaderRoute: typeof DashboardFoldersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/share/$pageId': {
      id: '/share/$pageId'
      path: '/share/$pageId'
      fullPath: '/share/$pageId'
      preLoaderRoute: typeof SharePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/p/$pageId': {
      id: '/dashboard/p/$pageId'
      path: '/p/$pageId'
      fullPath: '/dashboard/p/$pageId'
      preLoaderRoute: typeof DashboardPPageIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFoldersRoute: typeof DashboardFoldersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPPageIdRoute: typeof DashboardPPageIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFoldersRoute: DashboardFoldersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPPageIdRoute: DashboardPPageIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SharePageIdRoute: SharePageIdRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
